# @format

services:
   cooking:
      container_name: cooking-api
      restart: always
      image: node:20.10.0
      ports:
         - 4007:3003
      volumes:
         - ./:/usr/src/cooking
      working_dir: /usr/src/cooking
      networks:
         - monorepo-network
      environment:
         - PORT=3003
         - MONGO_URL=mongodb+srv://example:4ROohect0dIdKT13@cluster0.gudhgmq.mongodb.net/Burak
         - SESSION_SECRET=jwnfjknewfjnwefjnjwenf
         - SECRET_TOKEN=iwnfuiwenfuwej342minqdin!2r

      command: bash -c "npm install && npm run build && npm run start"
